### ISSUE TITLE
Split out SqsAdapter into its own repo

### ISSUE THREAD

**Issue by h-bragg** [graze/queue#12]
How about creating a separate repository for each different adapter configuration that requires third party libraries. Not technically required currently I guess as its injected into the adapter, but would be nice to be consistent if others are added in the future.

Current change would split out the sqs stuff into:
`graze/queue-sqs`

Which would contain the SqsAdapter and composer.json with requires: aws

**Comment by sjparkinson** [comment]
I think this is a good idea.

Much like Behat\Mink and it's various drivers.

I'll make sure to do this for #8, and will:

- [ ] Split out `SqsAdapter` into it's own repository/package

**Comment by sjparkinson** [comment]
@h-bragg I'm going to close this, while I think it's useful, for now it'll be a lot easier to manage while it's all in the same repository. Down the line though I don't see why not.

**Comment by h-bragg** [comment]
:+1:
