### ISSUE TITLE
Implement purging of queues

### ISSUE THREAD

**Issue by mathieupinet** [graze/queue#14]
Is there a plan to have support for the PurgeQueue() SQS API call to delete all messages in a queue?

**Comment by sjparkinson** [comment]
Clearing / purging a queue seems to be a generally supported feature for messaging systems.

I'm up for implementing this. Initial thoughts:

* Add `public function purge();` to `AdapterInterface`
* Add `public function purge();` to `ProducterInterface`
* Add a `UnsupportedOperationException` for adapters that may not support this feature
