### ISSUE TITLE
Support deleting queues

### ISSUE THREAD

**Issue by h-bragg** [graze/queue#19]
Enable deleting the queue functionality!

**Comment by sjparkinson** [comment]
Mind including some use cases / workflows?

I'm trying to think how this would work for the ArrayAdapter, and if it should be supported.

Will asked a good question in #16, "can every implementation support purging", and I should ask the same question here. For Kafka, it doesn't look like any of the php clients support deleting topics. Beanstalkd is a little weird in that the queue/topic lives on the port.

I think the answer is that deleting topics/queues/channels is perhaps too client specific to support a general for, unless we're willing to go down the route of `throw NotSupportedException`.

Thoughts?

**Comment by h-bragg** [comment]
This might be based on what we are using it for, but as part of a batch processing we create a queue for each batch of jobs to be processed. Once we have finished the batch we would like to tidy up (delete the queue).

Currently this client owns everything about the queue so it would be hard to do it outside.
