### ISSUE TITLE
Handle individual message handling failures without failing a batch

### ISSUE THREAD

**Issue by h-bragg** [graze/queue#23]
Currently when grabbing messages from the queue, if any of the messages fail, all messages after that will be marked as having failed / increased its retry count.

It would be nice to have:
- (soft?) failure of messages. Instead of the only way a message can fail is throwing an exception, be able to mark a message as failed but we want to continue processing the rest of the messages.

Thoughts?

**Comment by sjparkinson** [comment]
So we're going to look at updating the three concrete handlers to check if `$result` is strictly equal to `false` and skip acknowledgment if that's the case.

**Comment by h-bragg** [comment]
:+1:

**Comment by sjparkinson** [comment]
So, checkout https://github.com/graze/queue/commit/38c030fdacb01d898f52158e1a98aa7f0881ea4e.

I'm not sure this is a great practice though, will it not mean if workers are all going to skip acknowledgment of a bad message then that message will continue to get dequeued until the end of time?

I'm actually really leaning towards asking you to implement your own handler for this specific case.
